### ISSUE TITLE
Finality param, use new endpoint

### ISSUE THREAD

**Issue by dndll** [near/rollup-data-availability#100]
**Is your feature request related to a problem? Please describe.**

We should expose some finality parameter to users in the client, with a default to wait for full finality. Use the newer `send_tx` 

https://docs.near.org/api/rpc/transactions#send-tx
https://docs.near.org/api/rpc/transactions#tx-status-result

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Momendwiri** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> We should expose some finality parameter to users in the client, with a default to wait for full finality. Use the newer `send_tx`
> 
> https://docs.near.org/api/rpc/transactions#send-tx https://docs.near.org/api/rpc/transactions#tx-status-result
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

Sent to: cd9b9351fd8ec40c8e82df9803e911c30064c6a07d4e156df2880b2a5290e58c
