### ISSUE TITLE
Polling and finality

### ISSUE THREAD

**Issue by dndll** [near/rollup-data-availability#101]
**Is your feature request related to a problem? Please describe.**
Sometimes submissions are being timed out, we should do some tidyup to the da rpc, namely:
- bump near-jsonrpc-client to latest
- enforce full finality on submissions, in the `wait_until` field in the request.
- use `broadcast_tx_async` and poll for the result, if it fails, send again with some backoff. Investigate if `near-fetch` has permissive enough dependencies to do this for free.

https://github.com/near/rollup-data-availability/issues/76
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by firatNEAR** [comment]
Is this resolved by https://github.com/near/rollup-data-availability/pull/94 ?
