### ISSUE TITLE
[WIP] Data Availability Sampling

### ISSUE THREAD

**Issue by carrion256** [near/rollup-data-availability#18]
As of writing this issue, we provide DAS 0.1, which exposes merkle inclusion proofs over a HTTP API in the light client. The workflow is as follows:

**Assume client is synced**

L2 -> Contract: Submits blob at `Tx(ABC)`
Contract returns `[height, blob_commitment_root]`
L2 -> L1: `[height, blob_commitment_root]`
Anyone can find the transaction id for height
Anyone -> Light client/Validator/Archive: request inclusion proof for `transaction id` OR `receipt`
Anyone can manually calculate inclusion of the transaction/receipt, if adept enough
Anyone -> Light client: Verify proof
Anyone can read the contract store at `blob_commitment_root` and calculate the root themselves

This works off of an assumption that NEAR validators:
- have not been compromised
- will not withhold proofs to the light client (currently get_light_client_proof is EXPERIMENTAL)
- have not removed the data
- will hold the data for a period of time

As well as the light client:
- is synced correctly
- has not been subject to a long range attack
- has the canonical head
- will not withhold proofs to the user

To limit trust assumptions, we have to

**Comment by dndll** [comment]
https://github.com/near/rollup-data-availability/pull/53 - partway erasure commitments

**Comment by dndll** [comment]
https://github.com/near/rollup-data-availability/pull/58 - Slight point compression

**Comment by dndll** [comment]
We need to decide if we can do DAS with protocol or additional network after integration

https://github.com/near/rollup-data-availability/issues/60
