### ISSUE TITLE
C.submit_batch. return error: "NEAR DA client handler error: [Timeout]" when a large data

### ISSUE THREAD

**Issue by elvis-hp** [near/rollup-data-availability#76]
C.submit_batch. return error: "NEAR DA client handler error: [Timeout]"
How to fix this?

**Comment by elvis-hp** [comment]
up!
Please help me...

**Comment by dndll** [comment]
Interesting. Could you share some of the payload you're sending? Also, whats your RPC config?

**Comment by iavl** [comment]
It is intermittent on testnet, I encountered it a few days ago

**Comment by firatNEAR** [comment]
@iavl could you provide the payload that you are sending to the da-rpc?

**Comment by iavl** [comment]
> @iavl could you provide the payload that you are sending to the da-rpc?

https://explorer.testnet.near.org/transactions/EN5uFceXsTksmiRpsax2HdmgNshYjSiPUJBxmsvze2JW

**Comment by dndll** [comment]
I think we can close this since [0.4.0](https://github.com/near/rollup-data-availability/releases/tag/v0.4.0)
